version: '3.8'

services:
  fastapi:
    container_name: 'fastapi'
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    networks:
      - app-network

  pgdb:
    container_name: 'pgdb'
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rich
      POSTGRES_DB: softiqo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data:/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:  # Persistent storage for PostgreSQL
    driver: local

networks:
  app-network:
    driver: bridge  # Ensure the network uses bridge mode